name: test-githubactionsdocker
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
 builds:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout 
    uses: actions/checkout@v2

  - name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
      Username: ${{ Secrets. DOCKER_HUB_USERNAME }}
      password: ${{ secrets. DOCKER_HUB_ACCESS_TOKEN }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Build and push
    uses: docker/build-push-action@v2
    with:
     context: .
     file: ./Dockerfile
     push: true
     tags: lauaneoliveira/flask-web-docker:latest

  - 
    name: Build and push
    uses: docker/build-push-action@v2
    with:
     context: .
     file: ./2.Dockerfile
     push: true
     tags: lauaneoliveira/flask-web-docker:latest
